### PR TITLE
[WIP] Feature/#14 fix title

### LINKED ISSUE #14: タイトルの修正

### PR DESCRIPTION
**Pull request by hy-09**
close #14

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export default function Home() {
 
       <main className={styles.main}>
         <h1 className={styles.title}>
-          Function C-1 Welcome to <a href="https://nextjs.org">Next.js!</a>
```
Comment (hy-09) [inline pages/index.js:16]: why delete this?

Comment (hy-09) [reply pages/index.js:16]: no need

**Review by hy-09 — COMMENTED** [review]
hello

**Comment by hy-09** [comment]
hello!

**Review by hy-09 — COMMENTED** [review]
goodbye

**Review by hy-09 — COMMENTED** [review]
see you

**Comment by hy-09** [comment]
> aaaa

yes

**Comment by hy-09** [comment]
https://github.com/hy-09/github-frontend/pull/15#issuecomment-990551473

> > aaaa
> 
> yes

nice

**Comment by hy-09** [comment]
https://github.com/hy-09/github-frontend/pull/15#issuecomment-990551891

> [#15 (comment)](https://github.com/hy-09/github-frontend/pull/15#issuecomment-990551473)
> 
> > > aaaa
> > 
> > 
> > yes
> 
> nice

nice!
